MIN_gap_x=1.25 -- >1.35 sometimes is too wide a gap to detect
MIN_gap_y=1.45
margin=1.45
N_columns=2
white_point=255
option="(portrait) vertical scroll "..device.default_split
crop_T = 5
crop_B = 5
crop_L = 6.5
crop_R = 6.5
